name: test-file

on:
  pull_request:
    branches:
      - master

jobs:
  Validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Download-ref-repo
         run: |
           mkdir ~/ref-repo
           cd ~/ref-repo
           touch readme.md
           touch contributing.md
           echo "confidental" > readme.md
    
       - name: Download-source-repo
         run: |
            chmod +x ./validate-scripts/validator_pp.py
            python3 ./validate-scripts/validator_pp.py ~/ref-repo/

       - name: Dump-Github-context
         env:
           GITHUB_CONTEXT: ${{ toJSON(github) }}
         run: echo "$GITHUB_CONTEXT"
            
          
        
          
          
