name: test-file

on: workflow_dispatch

jobs:
  Download-Github-repo:
    runs-on : ubuntu-latest
    steps:
      - name: Create-Dir
        run: |
          mkdir ~/Test-Dir
          git --version
